"""initial schema

Revision ID: 3cdf8d7dbd1e
Revises: 
Create Date: 2026-07-16 11:39:08.098734

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '3cdf8d7dbd1e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('label')
    )
    op.create_table('iaec_agenda',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meeting_date', sa.Date(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('iaec_meeting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('minutes', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('iaec_project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('investigator_name', sa.String(), nullable=False),
    sa.Column('protocol_number', sa.String(), nullable=True),
    sa.Column('approval_date', sa.Date(), nullable=True),
    sa.Column('principal_investigator', sa.String(), nullable=True),
    sa.Column('purpose', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('objective', sa.String(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.create_table('species',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('animal_requisition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('protocol_id', sa.Integer(), nullable=False),
    sa.Column('requester_user_id', sa.Integer(), nullable=False),
    sa.Column('requester_name', sa.String(), nullable=False),
    sa.Column('requester_role', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('purpose', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['protocol_id'], ['iaec_project.id'], ),
    sa.ForeignKeyConstraint(['requester_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cage_label',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cage_id', sa.Integer(), nullable=False),
    sa.Column('label_text', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['cage_id'], ['cage.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('experiment_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['iaec_project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('form_b',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['iaec_project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('form_d_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['iaec_project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('iaec_amendment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['iaec_project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('iaec_minutes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['iaec_meeting.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('iaec_project_closure',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['iaec_project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('iaec_renewal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['iaec_project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('strain',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('species_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['species_id'], ['species.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_roles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('animal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('species_id', sa.Integer(), nullable=False),
    sa.Column('strain_id', sa.Integer(), nullable=False),
    sa.Column('cage_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('protocol_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cage_id'], ['cage.id'], ),
    sa.ForeignKeyConstraint(['protocol_id'], ['iaec_project.id'], ),
    sa.ForeignKeyConstraint(['species_id'], ['species.id'], ),
    sa.ForeignKeyConstraint(['strain_id'], ['strain.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('animal_allocation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requisition_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('allocated_by', sa.String(), nullable=False),
    sa.Column('remarks', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['requisition_id'], ['animal_requisition.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('animal_experiment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['experiment_group.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('animal_requisition_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requisition_id', sa.Integer(), nullable=False),
    sa.Column('species_id', sa.Integer(), nullable=False),
    sa.Column('strain_id', sa.Integer(), nullable=False),
    sa.Column('requested_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['requisition_id'], ['animal_requisition.id'], ),
    sa.ForeignKeyConstraint(['species_id'], ['species.id'], ),
    sa.ForeignKeyConstraint(['strain_id'], ['strain.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('form_b_animal_requirement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('form_b_id', sa.Integer(), nullable=False),
    sa.Column('species_id', sa.Integer(), nullable=False),
    sa.Column('strain_id', sa.Integer(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['form_b_id'], ['form_b.id'], ),
    sa.ForeignKeyConstraint(['species_id'], ['species.id'], ),
    sa.ForeignKeyConstraint(['strain_id'], ['strain.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('form_b_drug_injection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('form_b_id', sa.Integer(), nullable=False),
    sa.Column('drug_name', sa.String(), nullable=False),
    sa.Column('dose', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['form_b_id'], ['form_b.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('form_b_investigator',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('form_b_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['form_b_id'], ['form_b.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('procurement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('species_id', sa.Integer(), nullable=False),
    sa.Column('strain_id', sa.Integer(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['species_id'], ['species.id'], ),
    sa.ForeignKeyConstraint(['strain_id'], ['strain.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('animal_allocation_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('allocation_id', sa.Integer(), nullable=False),
    sa.Column('requisition_item_id', sa.Integer(), nullable=False),
    sa.Column('allocated_count', sa.Integer(), nullable=False),
    sa.Column('remaining_count', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['allocation_id'], ['animal_allocation.id'], ),
    sa.ForeignKeyConstraint(['requisition_item_id'], ['animal_requisition_item.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('animal_movement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('animal_id', sa.Integer(), nullable=False),
    sa.Column('from_cage_id', sa.Integer(), nullable=False),
    sa.Column('to_cage_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['animal_id'], ['animal.id'], ),
    sa.ForeignKeyConstraint(['from_cage_id'], ['cage.id'], ),
    sa.ForeignKeyConstraint(['to_cage_id'], ['cage.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('animal_weight',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('animal_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('weight_g', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['animal_id'], ['animal.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('experiment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('protocol_id', sa.Integer(), nullable=False),
    sa.Column('allocation_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('procedure', sa.String(), nullable=False),
    sa.Column('dose', sa.String(), nullable=False),
    sa.Column('observations', sa.String(), nullable=False),
    sa.Column('performed_by', sa.String(), nullable=False),
    sa.Column('purpose', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['allocation_id'], ['animal_allocation.id'], ),
    sa.ForeignKeyConstraint(['protocol_id'], ['iaec_project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('form_d_animal_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('animal_id', sa.Integer(), nullable=False),
    sa.Column('procedure', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['animal_id'], ['animal.id'], ),
    sa.ForeignKeyConstraint(['record_id'], ['form_d_record.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('allocation_item_animals',
    sa.Column('allocation_item_id', sa.Integer(), nullable=True),
    sa.Column('animal_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['allocation_item_id'], ['animal_allocation_item.id'], ),
    sa.ForeignKeyConstraint(['animal_id'], ['animal.id'], )
    )
    op.create_table('experiment_animal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('experiment_id', sa.Integer(), nullable=False),
    sa.Column('animal_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['animal_id'], ['animal.id'], ),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('experiment_animal')
    op.drop_table('allocation_item_animals')
    op.drop_table('form_d_animal_usage')
    op.drop_table('experiment')
    op.drop_table('animal_weight')
    op.drop_table('animal_movement')
    op.drop_table('animal_allocation_item')
    op.drop_table('procurement')
    op.drop_table('form_b_investigator')
    op.drop_table('form_b_drug_injection')
    op.drop_table('form_b_animal_requirement')
    op.drop_table('animal_requisition_item')
    op.drop_table('animal_experiment')
    op.drop_table('animal_allocation')
    op.drop_table('animal')
    op.drop_table('user_roles')
    op.drop_table('strain')
    op.drop_table('iaec_renewal')
    op.drop_table('iaec_project_closure')
    op.drop_table('iaec_minutes')
    op.drop_table('iaec_amendment')
    op.drop_table('form_d_record')
    op.drop_table('form_b')
    op.drop_table('experiment_group')
    op.drop_table('cage_label')
    op.drop_table('animal_requisition')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('species')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_table('roles')
    op.drop_table('iaec_project')
    op.drop_table('iaec_meeting')
    op.drop_table('iaec_agenda')
    op.drop_table('cage')
    # ### end Alembic commands ###